### ISSUE TITLE
Changing metric_type doesn't appear to change result from "Unblended"

### ISSUE THREAD

**Issue by thetombombadil** [electrolux-oss/aws-cost-exporter#27]
Hi again, thank you for the project.

Changing `metric_type` doesn't appear to have an effect - based on my findings it seems like it always retrieves the "Unblended" costs.

Image used: `opensourceelectrolux/aws-cost-exporter:v1.0.10`

Example:

Here's an account with daily cost of `~1674` using `Unblended costs` aggregation
![Image](https://github.com/user-attachments/assets/2eee1f0e-cf98-4e2f-b5c3-ccec478a57c7)

Same account with daily cost of `~1748` using `Amortized costs` aggregation
![Image](https://github.com/user-attachments/assets/ecf5bf7e-ab66-46b0-b1fa-d4e2d43155d2)

Now looking at aws-cost-explorer relevant snippet of config:

```yaml
metrics:
  - metric_name: aws_daily_cost_by_region_by_account
    group_by:
      enabled: true
      groups:
        - type: DIMENSION
          key: REGION
          label_name: Region
        - type: DIMENSION
          key: LINKED_ACCOUNT
          label_name: AccountName
      merge_minor_cost:
        enabled: true
        threshold: 10
        tag_value: Other
    metric_type: AmortizedCost

target_aws_accounts:
  - Publisher: 123456789012
 ```

Tested with `metric_type` set to both `AmortizedCost` and `UnblendedCost`, both equal `1674` which matches the unblended costs in console. I would expect when ` metric_type: AmortizedCost` the value in grafana would be `~1748` instead.

![Image](https://github.com/user-attachments/assets/075fb47f-6b33-4631-b596-200a73834e32)

Appreciate any time spent looking into this, thank you 🙏
