### ISSUE TITLE
Feature Request: Make RECORD_TYPE Filter Configurable for Cost Explorer Queries

### ISSUE THREAD

**Issue by fabiiw05** [electrolux-oss/aws-cost-exporter#28]
## Background
Currently, the RECORD_TYPE filter in AWS Cost Explorer queries is hardcoded to "Usage", making it impossible to include Savings Plans (SP) costs in the reported metrics.

https://github.com/electrolux-oss/aws-cost-exporter/blob/3c0a8472196f021a5be8aa56b3ecfda323949636/app/exporter.py#L113

As a result, important cost components such as:

- SavingsPlanCoveredUsage
- SavingsPlanRecurringFee
- SavingsPlanNegation

are not included in the metrics, leading to incomplete cost reporting.

## Proposed Improvement
Make the RECORD_TYPE filter configurable via the settings file (YAML or JSON).
This will allow users to customize which record types are included in cost calculations.

Example Configuration (YAML)
```
metrics:
  - metric_name: aws_daily_cost_by_service_by_account
    group_by:
      enabled: true
    metric_type: AmortizedCost
    record_types:
      - Usage
      - SavingsPlanCoveredUsage
      - SavingsPlanRecurringFee
      - SavingsPlanNegation
```

## Benefits
Allows users to include Savings Plans costs in their metrics.
Increases flexibility by making it easy to adjust the RECORD_TYPE filter.
Maintains backward compatibility:
If no configuration is provided, it defaults to ["Usage"], preserving the existing behavior.

## Potential Impact
No breaking changes, as "Usage" remains the default.
Users who want more detailed cost reporting can enable additional RECORD_TYPE values.

## Additional Information
AWS Cost Explorer RECORD_TYPE Reference:
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/viewing-aws-costs.html

If this proposal is accepted, I would be happy to submit a pull request (PR) to implement the changes.
Please let me know your thoughts! 🚀
