### ISSUE TITLE
Grafana 500 Error: Prometheus Query Fails Due to Negative Offset Issue

### ISSUE THREAD

**Issue by adityaculvii** [electrolux-oss/aws-cost-exporter#37]
Hi,

We are encountering the following issue in the Grafana dashboard:

**Status: 500. Message: bad_data: negative offset is disabled, use --enable-feature=promql-negative-offset to enable it**

Setup Details:

    Prometheus Operator: Running on Amazon EKS

    Prometheus Version: v2.30.0

    Grafana Version: 10.2.0

Problem Description:

We're seeing a blank (empty) value for the aws_cost query in Grafana, even though the underlying aws_daily_cost_by_service_by_account query returns valid data when executed directly in Prometheus.
Exporter Logs:

```

2025-06-30 11:24:20,399 INFO     Querying cost data for AWS account 039074xxxxxx
2025-06-30 11:24:20,906 INFO     Querying cost data for AWS account 039074xxxxxx

```
Possible Cause:

The error message indicates that the PromQL query uses a negative offset, which is disabled by default in Prometheus v2.30.0. To resolve this, you’ll need to enable the promql-negative-offset feature flag by adding the following Prometheus command-line argument:

--enable-feature=promql-negative-offset

is this really required?

**Comment by adityaculvii** [comment]
Hi @gluckzhang thank you for the updated , but is there any reason why aws_cost metric is empty in my case?

**Comment by gluckzhang** [comment]
> Hi [@gluckzhang](https://github.com/gluckzhang) thank you for the update , but is there any reason why aws_cost metric is empty in my case?

Could you please check which version are you using, and try `curl` the metric endpoint directly? Also you can check the `metric_name` field in the config file and see what is the metric name. Let me know if you have new findings there, happy to help you further once we get some details.

**Comment by adityaculvii** [comment]
Hi @gluckzhang thanks you for the response ,


I am currently using exporter version v1.0.11.

Here is the configuration I'm using:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-cost-exporter-config
  namespace: aws-cost-exporter
data:
  exporter_config.yaml: >
    exporter_port: $EXPORTER_PORT|9090  # Port exposing the cost metrics

    polling_interval_seconds: $POLLING_INTERVAL_SECONDS|28800  # Defaults to 8 hours since AWS updates daily cost data once per day

    aws_access_key: $AWS_ACCESS_KEY|""  # For production, leave this blank to use IAM role/IRSA

    aws_access_secret: $AWS_ACCESS_SECRET|""  # For production, leave this blank to use IAM role/IRSA

    aws_assumed_role_name: $AWS_ASSUMED_ROLE|""  # Optional. If empty, uses instance profile. Otherwise, specify the role name to assume

    metrics:
      - metric_name: aws_daily_cost_by_service_by_account
        group_by:
          enabled: true
          groups:
            - type: DIMENSION
              key: SERVICE
              label_name: ServiceName
            - type: DIMENSION
              key: LINKED_ACCOUNT
              label_name: AccountName
          merge_minor_cost:
            enabled: false
            threshold: 10
            tag_value: other
        metric_type: AmortizedCost
        record_types:
          - Usage
          - SavingsPlanCoveredUsage

      - metric_name: aws_daily_cost_usd
        group_by:
          enabled: true
          groups:
            - type: DIMENSION
              key: SERVICE
              label_name: ServiceName
            - type: DIMENSION
              key: REGION
              label_name: RegionName
          merge_minor_cost:
            enabled: false
            threshold: 10
            tag_value: other
        metric_type: AmortizedCost

    target_aws_accounts:
      - Publisher: 039074742030
        ProjectName: sadbox
        EnvironmentName: sandbox
```

Regarding the dashboard JSON at this link:
https://github.com/electrolux-oss/aws-cost-exporter/blob/main/doc/aws-cost-overview-dashboard-example.json

This dashboard seems to be using the metric name aws_cost. is it not updated?

However, in above configmap, the metric name is aws_daily_cost_by_service_by_account.
Should i update the the configmap metric name to aws_cost? to match it with dashboard json?
